### ISSUE TITLE
MANQUE++ - ${DATA}/downloads:/downloads

### ISSUE THREAD

**Issue by buddyqc69** [Keb83-Qc/serveur-multimedia#1]
https://github.com/Keb83-Qc/serveur-multimedia/blob/a29c21b73070310becfb15a0b41ff63951c8945f/docker-compose.yml#L52

```
sonarr:
    image: [lscr.io/linuxserver/sonarr:latest](http://lscr.io/linuxserver/sonarr:latest?fbclid=IwAR0aScXnu0HqEOFZDzB6hovB9oD2Z_P3qBaixA9oE8I3FnujlWtWY53mxyc)
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${DATA}/tvseries:/tv
      - ${DATA}/downloads:/downloads
    ports:
      - ${SONARR_PORT}:${SONARR_PORT}
    restart: unless-stopped
```
